import json

with open("eval_local.ipynb", "r") as f:
    nb = json.load(f)

for cell in nb["cells"]:
    if cell["cell_type"] == "code":
        source = "".join(cell["source"])
        if "endpoint_url=r2_endpoint," in source:
            # We will just replace the entire broken block with a clean load setup
            lines = source.split('\n')
            new_lines = []
            skip = False
            for line in lines:
                if "# Pull latest checkpoints from R2" in line:
                    skip = True
                    new_lines.append("# Relying on local checkpoints generated by train.py")
                
                if "# Find highest generation checkpoint dynamically" in line:
                    skip = False
                    
                if not skip:
                    new_lines.append(line)
            source = "\n".join(new_lines)
            cell["source"] = [line + "\n" if not line.endswith("\n") else line for line in source.split("\n")][:-1]

with open("eval_local.ipynb", "w") as f:
    json.dump(nb, f, indent=1)

